server:
  port: 8000

spring:
  application:
    name: api-gateway

eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@localhost:7000/eureka/

zuul:
  routes:
    micro-service-user: /userService/**
    micro-service-activity: /activityService/**
