server:
  port: 8000

spring:
  application:
    name: api-gateway

eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@localhost:7000/eureka/,http://admin:admin@localhost:7001/eureka/

zuul:
  routes:
    micro-service-user: /userService/**
    micro-service-activity: /activityService/**
  host:
    connect-timeout-millis: 15000
    socket-timeout-millis: 60000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
