spring:
  application:
    name: micro-service-user
  cloud:
    bus:
      trace:
        enabled: true
      enabled: true

server:
  port: 8181

management:
  endpoints:
    web:
      exposure:
        include: bus-refresh



