spring:
  application:
    name: eureka-server
  security:
    user:
      name: admin
      password: admin

server:
  port: 7000

eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@localhost:${server.port}/eureka/
    fetch-registry: false
    register-with-eureka: false