spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/ars
  application:
    name: micro-service-user

server:
  port: 8181

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7000/eureka/


